version: "3.10"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/main
    environment:
      - APP_HOME=/main
    command: ["python", "main.py"]
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
